reference_source: ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/genomic/c_elegans.PRJNA13758.WS245.genomic.fa.gz
genome_name: WS245
num_locations: 150
num_location_files: 3
bam_location: /lscr2/andersenlab/dec211/RUN/20150727_RIAIL/bam/E300.bam
joint_bam_path: /lscr2/andersenlab/dec211/RUN/20150727_RIAIL/bam
joint_bams:
  - E351
  - E35
joint_set2:
  - CB4856
  - DL238
  - LKC34
  - JT11398
  - ED3017
  - MY16
  - MY23
  - JU775
  - JU258
  - EG4725
  - CX11314
  - PB306
  - CX11276
  - AB1
  - JU847
  - JU1896
  - WN2002
  - JU1652
  - ED3011
  - JU1200
