reference_source: ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/genomic/c_elegans.PRJNA13758.WS245.genomic.fa.gz
genome_name: WS245
num_locations: 100000
num_location_files: 10
bam_location: /lscr2/andersenlab/dec211/RUN/v2_snpset/bam/N2.bam
reference_sample: N2
joint_bam_path: /lscr2/andersenlab/dec211/RUN/v2_snpset/bam
joint_bams:
  - CB4856
  - DL238
  - LKC34
  - JT11398
  - ED3017
  - MY16
  - MY23
  - JU775
  - JU258
  - EG4725
  - CX11314
  - PB306
  - CX11276
  - AB1
  - JU847
  - JU1896
  - WN2002
  - JU1652
  - ED3011
  - JU1200
