reference_source: ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/sequence/genomic/c_elegans.PRJNA13758.WS245.genomic.fa.gz
genome_name: WS245
num_locations: 150
num_location_files: 3
bam_location: /Users/dancook/Documents/git/variant-caller-analysis/test/QX175.sorted.bam